services:
  minio:
    image: "${DOCKER_IMAGE_NAME}"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_API_PORT_NUMBER: "${MINIO_API_PORT_NUMBER}"
      MINIO_CONSOLE_PORT_NUMBER: "${MINIO_CONSOLE_PORT_NUMBER}"
      MINIO_SCHEME: "${MINIO_SCHEME}"
      MINIO_SERVER_URL: "${MINIO_SERVER_URL}"
      MINIO_BROWSER_REDIRECT_URL: "${MINIO_BROWSER_REDIRECT_URL}"
    ports:
      - "${MINIO_API_PORT_NUMBER}:${MINIO_API_PORT_NUMBER}"
      - "${MINIO_CONSOLE_PORT_NUMBER}:${MINIO_CONSOLE_PORT_NUMBER}"
    volumes:
      # sudo chown -R 1001:1001 ./minio
      - ./minio:/bitnami/minio/data  
    restart: ${CONTAINER_RESTART}
